name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./Code/Light.Xunit.sln
    - name: Build
      run: dotnet build ./Code/Light.Xunit.sln -c Release --no-restore
    - name: Test
      run: dotnet test ./Code/Light.Xunit.Tests/Light.Xunit.Tests.csproj -c Release --no-build --verbosity normal
